version: "3"

services:
  mysql_serve:
    image: mysql:5.6.42
    container_name: db_healthatom
    ports:
      - 33060:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: healthatom_test
      MYSQL_ROOT_PASSWORD: 123456